// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcpesiwfkquvlpfbtdtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjcGVzaXdma3F1dmxwZmJ0ZHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTA4MjIsImV4cCI6MjA2NTE2NjgyMn0.63DCdrF9innne3Bis4iMZJQ25KHXGEAou4K05hmRpWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);